Code challenge completed
jrodrigoav/coe-net-training pull request #13
Opened 2022-10-22 00:53 UTC by JesusCN

# CHANGELOG

### FrontEnd: 
1) Fix all tests (do only Unit Tests) 
2) In Test API Page
     - Display returned message from test API
     - EXTRA: Add input for testing sent and responded message
3) In Users Page: 
     - Use new API from asp.net
     - Display in table: Name, Username, Email, and Phone. 
     - Unit Tests
3) In Albums Page: 
     - Use new API from asp.net
     - Display in table: Id, Title, and Username (from user). 
     - Unit Tests
4) In services: 
     - Add API service to consume Asp.net API instad of typicode. 

### Backend: 
1) Add controllers for getting Users and Albums from typicode

### TODO: 
- Add cache to backend.

2022-10-25 01:38 UTC, JesusCN commented
## Fixes after review
- Add OptionMonitor for reading configurations in Typicode Service.
- Add authentication to albums and user controllers. 
- Change ActionResult<T> to IActionResult in controllers.

2022-10-25 01:38 UTC, JesusCN commented
### EXTRA
- Buttons for login and logout in frontend proyect

2022-10-26 02:10 UTC, jrodrigoav approved these changes

2022-10-26 02:12 UTC, jrodrigoav requested changes
Branch has conflicts because I merged the previous pull request first it seems.

2022-11-21 20:46 UTC, closed without merging