Arthur code challenge1
jrodrigoav/coe-net-training pull request #15
Opened 2022-11-24 22:40 UTC by ArturoLozanoRdz

Test fixing is still WIP

2022-11-28 03:38 UTC, jrodrigoav requested changes
Reach out in Teams for questions regarding the comments

2022-11-28 03:38 UTC, jrodrigoav commented on backend/UnicornRewards.API.Models/Models/User.cs
> +    public class User
Use PascalCase for property names as a standard for C# unless otherwise indicated, this applies for everything in Unosquare

2022-11-28 03:38 UTC, jrodrigoav commented on backend/UnicornRewards.API/Controllers/AlbumController.cs
> +            HttpClient client = new HttpClient();
This should be an HttpClient Service

2022-11-28 03:38 UTC, jrodrigoav commented on backend/UnicornRewards.API/Controllers/UserController.cs
> +    [Route("[action]")]
Use explicit routes

2022-11-30 19:15 UTC, ArturoLozanoRdz reviewed
Implemented httpclient service

2023-08-15 02:01 UTC, closed without merging