add functions to save on localstorage
jrodrigoav/coe-net-training pull request #7
Opened 2022-08-01 22:10 UTC by mcantuunosquare

Add functionality to save on local storage the selected users on the contact list page.

2022-08-01 22:27 UTC, jrodrigoav requested changes
Looks good, though unit tests for the service should include tests for the additional methods that control the list.

2022-08-01 22:27 UTC, jrodrigoav commented on frontend/src/app/pages/contact-list/contact-list.component.ts
> +  private selectedUsersFile:string = "./selected_users.json";
What is this file for?

2022-08-01 22:31 UTC, marcocantugea commented on frontend/src/app/pages/contact-list/contact-list.component.ts
> +  private selectedUsersFile:string = "./selected_users.json";
sorry, I forgot to delete this line.

2022-08-02 21:23 UTC, jrodrigoav approved these changes
Looks good

2022-08-02 21:23 UTC, merged